### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by peterhoeg** [Darwinnn/crometheus#4]
Any chance to cut a new release with the recent fixes for crystal 1.4 ?

**Comment by Darwinnn** [comment]
Hi @peterhoeg unfortunately I lost interest in the project, but if you want to make a PR I'll be happy to merge it.

**Comment by Darwinnn** [comment]
Oh sorry, I didn't get you right. 
Yeah, since the changes to work on 1.4 have already been made I pushed a new release [0.4.0](https://github.com/Darwinnn/crometheus/releases/tag/0.4.0)
